import { Noto_Naskh_Arabic, Architects_Daughter } from "next/font/google";
import type { Metadata } from "next";
//@ts-ignore
import "../globals.css";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const sansFont = Architects_Daughter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const isRtl = lang === "ar-SY";

  return (
    <html lang={lang} dir={isRtl ? "rtl" : "ltr"}>
      <body className={`${sansFont.className} antialiased`}>
        <LanguageSwitcher currentLang={lang} />
        {children}
      </body>
    </html>
  );
}
