import type { Metadata } from "next";
import { Architects_Daughter } from "next/font/google";
//@ts-ignore
import "./globals.css";

const sansFont = Architects_Daughter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sansFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
